(()=>{
  'use strict';
  const SUITE_HOSTED=window.location.pathname.startsWith('/apps/bio/');
  const CALC_STATES=Object.freeze({idle:'Calculate',validating:'Validating…',calculating:'Calculating…',converging:'Converging…',converged:'Converged',attention:'Needs attention',failed:'Calculation failed',stale:'Recalculate'});
  const GUIDANCE_LABELS=Object.freeze({information:'Information',review:'Review',warning:'Warning',calculation_error:'Calculation error',critical:'Critical/system error'});
  let dirty=false,enhanceQueued=false,allowHandoff=false,pendingHandoffButton=null;

  function ensureSuiteCoreAssets(){
    if(!SUITE_HOSTED)return;
    for(const href of ['/static/suite_ui_tokens.css','/static/suite_application_shell.css']){
      if(!document.querySelector(`link[href="${href}"]`)){const link=document.createElement('link');link.rel='stylesheet';link.href=href;link.dataset.twdsShared='true';document.head.appendChild(link);}
    }
    if(!document.querySelector('script[src="/static/suite_application_shell.js"]')){const script=document.createElement('script');script.src='/static/suite_application_shell.js';script.defer=true;script.dataset.twdsShared='true';document.body.appendChild(script);}
  }
  function resolvedTheme(value){if(value==='light'||value==='dark')return value;return window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';}
  function applyTheme(value){const requested=['system','light','dark'].includes(value)?value:'system';document.documentElement.dataset.theme=resolvedTheme(requested);document.documentElement.dataset.themePreference=requested;const select=document.getElementById('themeSelect');if(select)select.value=requested;return requested;}
  function setTheme(value){const requested=['system','light','dark'].includes(value)?value:'system';try{localStorage.setItem('twds-theme',requested);}catch(_){ }return applyTheme(requested);}
  function initTheme(){let saved='system';try{saved=localStorage.getItem('twds-theme')||'system';}catch(_){ }applyTheme(saved);document.getElementById('themeSelect')?.addEventListener('change',e=>setTheme(e.target.value));if(window.matchMedia){const mq=window.matchMedia('(prefers-color-scheme: dark)');mq.addEventListener?.('change',()=>{if(document.documentElement.dataset.themePreference==='system')applyTheme('system');});}}

  function setCalcState(state,detail=''){
    if(!CALC_STATES[state])return;
    const button=document.getElementById('calculateBtn'),label=document.getElementById('calculateBtnLabel'),legacy=document.getElementById('calcState'),live=document.getElementById('calculationLive');
    if(button){button.dataset.twdsCalculateState=state;button.setAttribute('aria-busy',['validating','calculating','converging'].includes(state)?'true':'false');}
    if(label)label.textContent=CALC_STATES[state];
    if(legacy&&legacy.textContent!==CALC_STATES[state])legacy.textContent=CALC_STATES[state];
    if(live)live.textContent=detail||CALC_STATES[state];
  }
  function guidanceCard(severity,title,message){const key=GUIDANCE_LABELS[severity]?severity:'information',css=key.replace('_','-');return `<section class="twds-guidance twds-guidance--${css}" role="${['calculation_error','critical'].includes(key)?'alert':'status'}"><div class="twds-guidance__marker" aria-hidden="true"></div><div class="twds-guidance__body"><strong><span class="guidance-severity">${GUIDANCE_LABELS[key]}</span> · ${escapeHtml(title)}</strong><p>${escapeHtml(message)}</p></div></section>`;}
  function setGuidance(severity,title,message){const host=document.getElementById('globalGuidance');if(host)host.innerHTML=guidanceCard(severity,title,message);}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));}

  function syncLegacyCalculationState(rawText){
    const raw=String(rawText||'').trim(),lower=raw.toLowerCase();
    if(Object.values(CALC_STATES).includes(raw)){if(raw==='Recalculate')setGuidance('review','Inputs changed','Review the updated basis and recalculate the biological process network.');return;}
    if(lower.includes('calculation issue')||lower.includes('failed')){setCalcState('failed');setGuidance('calculation_error','Calculation failed','One or more biological calculations require review before the result can be used.');}
    else if(lower.includes('missing')||lower.includes('bypassed')){setCalcState('attention');setGuidance('review','Needs attention','Required design inputs or planning assumptions require engineering review.');}
    else if(lower.includes('review')){setCalcState('attention');setGuidance('warning','Convergence requires review','Review the process configuration, recycle connections and residuals constraints.');}
    else if(lower.includes('current')||lower.includes('converged')){setCalcState('converged');setGuidance('information','Converged','Biological process, recycle, water-balance and residuals results are current.');}
    else setCalcState('idle');
  }
  function watchCalculationState(){const legacy=document.getElementById('calcState');if(!legacy)return;let internal=false;const observer=new MutationObserver(()=>{if(internal)return;internal=true;const raw=legacy.textContent;syncLegacyCalculationState(raw);internal=false;});observer.observe(legacy,{childList:true,characterData:true,subtree:true});syncLegacyCalculationState(legacy.textContent);}

  function markDirty(value=true){dirty=Boolean(value);const el=document.getElementById('unsavedIndicator');if(el)el.hidden=!dirty;document.querySelector('.bio-project-bar')?.setAttribute('data-twds-dirty',dirty?'true':'false');if(dirty)setCalcState('stale','Inputs changed. Recalculate the biological process network.');}
  function initDirtyTracking(){const main=document.getElementById('main');main?.addEventListener('input',e=>{if(e.target.matches('input,select,textarea'))markDirty(true);});main?.addEventListener('change',e=>{if(e.target.matches('input,select,textarea'))markDirty(true);});document.addEventListener('click',e=>{if(e.target.closest('.train-add,.train-remove,[data-unit-type],[data-recycle-enabled],[data-source-check],#addRecycle'))markDirty(true);});document.getElementById('saveBtn')?.addEventListener('click',()=>setTimeout(()=>markDirty(false),250));document.getElementById('newBtn')?.addEventListener('click',()=>setTimeout(()=>markDirty(false),0));document.getElementById('openBtn')?.addEventListener('click',()=>setTimeout(()=>markDirty(false),500));window.addEventListener('beforeunload',e=>{if(!dirty)return;e.preventDefault();e.returnValue='';});}

  const WORKSPACES={MarketIntake:'Client / RFQ Inputs',DesignBasis:'Detailed Design Basis',Dashboard:'Design Dashboard',MassBalance:'Process Mass Balance',CompactReport:'Compact Design Report'};
  function clickLegacyWorkspace(target){const wanted=WORKSPACES[target];const button=[...document.querySelectorAll('#nav button')].find(b=>b.textContent.includes(wanted));if(button){button.click();return true;}return false;}
  function syncWorkspaceNav(){const title=document.querySelector('#main .page-title h1')?.textContent||'';let target='DesignBasis';for(const [id,label] of Object.entries(WORKSPACES)){if(title.includes(label)||title.includes(label.replace('Design ','').replace('Compact ',''))){target=id;break;}}if(title.includes('Biological Treatment Design Dashboard'))target='Dashboard';if(title.includes('Process Mass Balance'))target='MassBalance';if(title.includes('Compact Design Report'))target='CompactReport';document.querySelectorAll('[data-workspace-target]').forEach(b=>{const active=b.dataset.workspaceTarget===target;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});}
  function initWorkspaceNav(){document.querySelectorAll('[data-workspace-target]').forEach(b=>b.addEventListener('click',()=>clickLegacyWorkspace(b.dataset.workspaceTarget)));}

  function recalculate(){
    setCalcState('validating','Validating biological design inputs…');
    requestAnimationFrame(()=>{setCalcState('calculating','Calculating biological process duties…');requestAnimationFrame(()=>{setCalcState('converging','Converging water, recycle and residuals networks…');setTimeout(()=>{try{if(window.TotalBioDesignUI?.recalculate)window.TotalBioDesignUI.recalculate();else clickLegacyWorkspace('Dashboard');setTimeout(()=>syncLegacyCalculationState(document.getElementById('calcState')?.textContent),0);}catch(err){setCalcState('failed',err?.message||'Calculation failed');setGuidance('calculation_error','Calculation failed',err?.message||'The biological calculation could not be completed.');}},0);});});
  }
  function initCalculate(){document.getElementById('calculateBtn')?.addEventListener('click',recalculate);}

  function syncProjectIdentity(){const name=document.getElementById('projectName'),id=document.getElementById('projectIdText'),rev=document.getElementById('projectRevisionText');if(!name)return;const match=String(name.textContent||'').match(/^(TBIO-\d+-(\d+))\s+·\s+(.+)$/);if(match){if(id)id.textContent=match[1];if(rev)rev.textContent=`Rev ${match[2]}`;if(name.textContent!==match[3])name.textContent=match[3];}else if(id&&!id.textContent.startsWith('TBIO-'))id.textContent='TBIO · not yet saved';}
  function watchProjectIdentity(){const name=document.getElementById('projectName');if(!name)return;new MutationObserver(syncProjectIdentity).observe(name,{childList:true,characterData:true,subtree:true});syncProjectIdentity();}

  async function initAccount(){if(!SUITE_HOSTED)return;try{const r=await fetch('/api/suite/session',{credentials:'same-origin',headers:{Accept:'application/json'}});const data=await r.json();if(!r.ok)return;const account=data.account;if(!account)return;const menu=document.getElementById('accountMenu'),full=String(account.full_name||account.email||'Suite user'),tier=String(account.licensed_tier||'entry');if(menu)menu.hidden=false;document.getElementById('accountAvatar').textContent=(full[0]||'U').toUpperCase();document.getElementById('accountName').textContent=full;document.getElementById('accountTier').textContent=tier.charAt(0).toUpperCase()+tier.slice(1);document.getElementById('accountPanelName').textContent=full;document.getElementById('accountEmail').textContent=String(account.email||'');document.getElementById('accountRole').textContent=`${String(account.role||'user')} · ${tier.charAt(0).toUpperCase()+tier.slice(1)}`;}catch(_){ }}

  function addOriginMarker(cell,text,cls=''){if(!cell||cell.querySelector(`.twds-origin-label.${cls||'origin'}`))return;const marker=document.createElement('div');marker.className=`subnote twds-origin-label ${cls||'origin'}`;marker.textContent=text;cell.appendChild(marker);}
  function enhanceInputs(){document.querySelectorAll('#main .input-control').forEach(el=>{el.classList.add('twds-origin-user');el.dataset.origin='user';const wrap=el.closest('.input-wrap');if(wrap){wrap.classList.add('twds-field--user');const sub=wrap.closest('tr')?.querySelector('.pname .subnote');if(sub)sub.textContent='User Input';if(el.hasAttribute('min')||el.hasAttribute('max')){if(!wrap.querySelector('.twds-constraint-marker')){const m=document.createElement('span');m.className='twds-constraint-marker';m.textContent='Constraint';wrap.appendChild(m);}}}});document.querySelectorAll('#main .result').forEach(el=>{el.classList.add('twds-origin-calculated');el.dataset.origin='calculated';addOriginMarker(el.closest('.valuecell'),'Calculated','calculated');});document.querySelectorAll('#main .picker-unit').forEach(el=>{el.classList.add('twds-origin-database');el.dataset.origin='database';});const stats=document.querySelector('#main .sheet-stats');if(stats){stats.innerHTML='<span class="chip input-chip">User Input</span><span class="chip key-chip">Calculated</span><span class="chip">Database</span><span class="chip">Constraint</span>';}}
  function categoryBefore(target,label,title){if(!target||target.previousElementSibling?.classList.contains('twds-result-category'))return;const div=document.createElement('div');div.className='twds-result-category';div.innerHTML=`<span>${label}</span><strong>${title}</strong>`;target.before(div);}
  function enhanceResults(){const main=document.getElementById('main');if(!main)return;const title=main.querySelector('.page-title h1')?.textContent||'';if(title.includes('Biological Treatment Design Dashboard')){categoryBefore(main.querySelector('.kpi-grid'),'System Summary','Major biological-treatment KPIs');main.querySelectorAll('.panel h3').forEach(h=>{const t=h.textContent;if(h.previousElementSibling?.classList.contains('twds-result-eyebrow'))return;let label='Process / Unit Summary';if(t.includes('Aeration & Energy'))label='Energy';const span=document.createElement('span');span.className='twds-result-eyebrow';span.textContent=label;h.before(span);});const warning=main.querySelector('.network-warning');if(warning)warning.classList.add('bio-warning-contract');const exportBtn=main.querySelector('#exportTotalRO');if(exportBtn)exportBtn.textContent='Handoff to Total RO Design';}else if(title.includes('Process Mass Balance'))categoryBefore(main.querySelector('.page-head')?.nextElementSibling,'Detailed Results','Process mass balance and stream detail');syncWorkspaceNav();}
  function queueEnhance(){if(enhanceQueued)return;enhanceQueued=true;requestAnimationFrame(()=>{enhanceQueued=false;enhanceInputs();enhanceResults();syncProjectIdentity();});}
  function watchWorkspace(){const main=document.getElementById('main');if(!main)return;new MutationObserver(queueEnhance).observe(main,{childList:true,subtree:true});queueEnhance();}

  function concentration(stream,key){const q=Number(stream?.flow)||0,m=Number(stream?.mass?.[key])||0;return q>0?m*1000/q:0;}
  function showHandoff(button){pendingHandoffButton=button;const dialog=document.getElementById('handoffDialog');if(!dialog)return;syncProjectIdentity();document.getElementById('handoffSourceProject').textContent=`${document.getElementById('projectIdText')?.textContent||''} · ${document.getElementById('projectName')?.textContent||'Current project'}`;document.getElementById('handoffLineage').textContent=document.getElementById('projectIdText')?.textContent||'Pending save';const net=window.TotalBioDesignUI?.getLastNetwork?.();const s=net?.water?.finalEffluent;if(s){const rows=[['Flow',`${Number(s.flow).toFixed(2)} m³/d`],['Temperature',`${Number(s.temperatureC||20).toFixed(1)} °C`],['pH',Number(s.pH||7).toFixed(2)],['BOD₅',`${concentration(s,'bod').toFixed(2)} mg/L`],['TSS',`${concentration(s,'tss').toFixed(2)} mg/L`],['NH₄-N',`${concentration(s,'nh4').toFixed(2)} mg/L`],['TP',`${concentration(s,'tp').toFixed(2)} mg/L`]];document.getElementById('handoffStreamSummary').innerHTML=rows.map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');}else document.getElementById('handoffStreamSummary').innerHTML='<div><span>Stream</span><strong>Recalculate before handoff</strong></div>';dialog.showModal?.();}
  function initHandoff(){document.addEventListener('click',e=>{const button=e.target.closest('#sendToROBtn,#exportTotalRO');if(!button||allowHandoff)return;e.preventDefault();e.stopImmediatePropagation();showHandoff(button);},true);const close=()=>document.getElementById('handoffDialog')?.close();document.getElementById('cancelHandoffBtn')?.addEventListener('click',close);document.getElementById('handoffCloseBtn')?.addEventListener('click',close);document.getElementById('confirmHandoffBtn')?.addEventListener('click',()=>{const target=SUITE_HOSTED?(document.getElementById('sendToROBtn')||pendingHandoffButton):pendingHandoffButton;close();if(!target)return;allowHandoff=true;target.click();setTimeout(()=>{allowHandoff=false;pendingHandoffButton=null;},0);});}

  function initProjectExtras(){const saveAs=document.getElementById('saveAsBtn'),dup=document.getElementById('duplicateBtn');if(SUITE_HOSTED){for(const b of [saveAs,dup])if(b){b.disabled=true;b.title='This project lifecycle action is not yet supported by the hosted Bio project API.';}}else{if(saveAs)saveAs.addEventListener('click',()=>document.getElementById('saveBtn')?.click());if(dup)dup.addEventListener('click',()=>document.getElementById('saveBtn')?.click());}}

  function init(){ensureSuiteCoreAssets();initTheme();initAccount();watchCalculationState();initDirtyTracking();initWorkspaceNav();initCalculate();watchProjectIdentity();watchWorkspace();initHandoff();initProjectExtras();setGuidance('information','Total Bio Design','Define the biological treatment basis, validate inputs, calculate the coupled process network, review convergence, then report or hand off the solved effluent.');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
