name: PR

on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  ci:
    uses: total-water-design/paperclip/.github/workflows/pr-trusted.yml@cec8ac25d998bcce5f51cf49645f79998becebaf
